### ISSUE TITLE
[NEW GOAL] Get Hunger effect

### ISSUE THREAD

**Issue by rybak** [Joshimuz/mcbingo#78]
**Name of the Goal**
"Get Hunger effect" or "Get effect Hunger"

**Difficulty level**
Very Easy. "(5-15) Rotten Flesh" is currently in Very Easy. Even without Rotten Flesh, Chickens are easy to find.

**Anti Synergies and Catalysts/Reactants**
"Pacifist", maybe. "Pacifist" is a Hard goal, so unlikely that these two will be on a same sheet. Also, when playing Bingo on Hard difficulty, finding Rotten Flesh in chests should be expected.

**Why this Goal is good**
A non item goal. Forces the player to think harder about food/hunger management.

**Comment by Joshimuz** [comment]
While "Become Nauseous" is just "Get Pufferfish" but with extra steps, at least those steps are:
1. 100% chance to happen, you only need to eat 1 Pufferfish to get it 100%
2. Not fully known as a mechanic
3. Somewhat funny to get a drunk effect

idk if this is, it's good because it's a non-item version of an item goal and has different ways to achieve it
Another problem is that "Hunger" is a common word and could get confused for just, being hungry so we have to add the word "effect" into it, which
1. Breaks naming convention as "Become Nauseous" doesn't have the word, but I guess we could add it
2. Still might cause confusion idk

Annoying because this is a good goal otherwise

**Comment by rybak** [comment]
In one of the recent bingos I couldn't find food, so resorted to Rotten Flesh. The "hunger management" for it wasn't as hard as I imagined.
